# Stage 1: Build
FROM node:20-slim AS build
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
# Build time variables
ARG VITE_AUTH_ENDPOINT=""
ARG VITE_API_BASE_URL=""
ARG VITE_INSTAGRAM_LINK=""
ARG VITE_FACEBOOK_LINK=""
ARG VITE_TIKTOK_LINK=""
ARG VITE_X_LINK=""
ARG VITE_LINKEDIN_LINK=""
ARG VITE_INTERCOM_APP_ID=""

# Set environment variables
ENV VITE_AUTH_ENDPOINT=$VITE_AUTH_ENDPOINT
ENV VITE_API_BASE_URL=$VITE_API_BASE_URL
ENV VITE_INSTAGRAM_LINK=$VITE_INSTAGRAM_LINK
ENV VITE_FACEBOOK_LINK=$VITE_FACEBOOK_LINK
ENV VITE_TIKTOK_LINK=$VITE_TIKTOK_LINK
ENV VITE_X_LINK=$VITE_X_LINK
ENV VITE_LINKEDIN_LINK=$VITE_LINKEDIN_LINK
ENV VITE_INTERCOM_APP_ID=$VITE_INTERCOM_APP_ID

RUN npm run build

# Stage 2: Serve
FROM nginx:alpine
COPY --from=build /app/dist /usr/share/nginx/html


